---
galaxy_info:
  author: Sean O'Shaughnessy
  description: Installs GlusterFS server/client packages
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: Ubuntu
      versions:
        - precise
    - name: Debian
      versions:
        - wheezy
  categories:
    - web
    - system
    - clustering
