---
- name: add git user account
  user: >
    name=git comment="Git Push User" state=present
    createhome=yes shell=/bin/bash system=yes
    generate_ssh_key=yes ssh_key_bits=2048

- name: add /home/git/.ssh/network.rsa
  template: >
    src=home-git-.ssh-network.rsa.j2
    dest=/home/git/.ssh/network.rsa
    owner=git group=git mode=0600

- name: add /home/git/.ssh/config
  template: >
    src=home-git-.ssh-config.j2
    dest=/home/git/.ssh/config
    owner=git group=git mode=0600

- name: add /home/git/.ssh/github.rsa
  template: >
    src=home-git-.ssh-github.rsa.j2
    dest=/home/git/.ssh/github.rsa
    owner=git group=git mode=0600

- name: clone gitolite to /opt/gitolite
  git: >
    repo=https://github.com/sitaramc/gitolite.git
    dest=/opt/gitolite force=no update=no

- name: run gitolite installer
  shell: >
    /opt/gitolite/install -ln /usr/local/bin

- name: run gitolite setup with public key from /home/git/.ssh
  shell: >
    su git -c '/usr/local/bin/gitolite setup -pk /home/git/.ssh/id_rsa.pub'

- name: add /home/git/.gitolite.rc
  copy: >
    src=home-git-.gitolite.rc
    dest=/home/git/.gitolite.rc
    owner=git group=git mode=0664

- name: add /opt/push-deploy
  file: >
    path=/opt/push-deploy state=directory
    owner=git group=git mode=2775

- name: add /opt/push-deploy/stage directories
  file: >
    path=/opt/push-deploy/{{ item }} state=directory
    owner=git group=git mode=2775
  with_items:
    - production
    - uat
    - staging
    - builds

- name: add /etc/cron.weekly/gitolite
  copy: >
    src=etc-cron.weekly-gitolite
    dest=/etc/cron.weekly/gitolite
    owner=root group=root mode=0644

- name: add /opt/tools/git
  file: >
    path=/opt/tools/git state=directory
    owner=root group=root mode=0755

- name: add /opt/tools/git/prune-branches-not-at-github
  copy: >
    src=opt-tools-git-prune-branches-not-at-github
    dest=/opt/tools/git/prune-branches-not-at-github
    owner=git group=git mode=0700

- name: add daily cron for prune-branches-not-at-github
  cron: >
    name="prune branches not at github"
    job="/opt/tools/git/prune-branches-not-at-github"
    user=git state=present
    minute="30" hour="8" day="*" month="*" weekday="*"

- include: configs.yml
- include: capistrano.yml
