---
- name: ensure terminus is installed
  get_url: >
    url=https://github.com/pantheon-systems/cli/releases/download/0.9.2/terminus.phar
    dest=/usr/local/bin/terminus
    owner=root group=staff mode=0755
  tags:
    - pantheon

- name: add /home/git/.ssh/pantheon.rsa
  template: >
    src=home-robot-.ssh-pantheon.rsa.j2
    dest=/home/git/.ssh/pantheon_robot_rsa
    owner=git group=git mode=0600
  tags:
    - pantheon