---
- name: add /etc/rc.local to update /etc/resolv.conf on boot
  copy: >
    src=etc-rc.local
    dest=/etc/rc.local
    owner=root group=root mode=0755

- name: create symlinks for development applications
  shell: >
    chdir=/nfs
    for project in $(/bin/ls); do
      if test -d /var/www/$project/htdocs ; then
        if test -d /var/www/$project/htdocs/current ; then
          rm -rf /var/www/$projects/htdocs/current;
        fi;
        ln -nfs /nfs/$project /var/www/$project/htdocs/current;
      fi;
    done
  ignore_errors: True
  changed_when: False
  tags:
    - client:provision
