---
- name: install dnsmasq packages
  apt: pkg=dnsmasq state=installed update_cache=yes cache_valid_time=86400

- name: add /etc/dnsmasq.conf
  template: >
    src=etc-dnsmasq.conf.j2
    dest=/etc/dnsmasq.conf
    owner=root group=root mode=0644
  notify: dnsmasq restart
  tags:
    - client:provision

- name: check if /etc/resolv.conf is a symlink
  shell: test -L /etc/resolv.conf
  register: dnsmasqEtcResolvSymlink
  ignore_errors: True
  changed_when: False

- name: remove /etc/resolv.conf symlink
  file: >
    path=/etc/resolv.conf state=absent
  when: dnsmasqEtcResolvSymlink.rc == 0

- name: unset immutable bit on /etc/resolv.conf
  shell: >
    chattr -i /etc/resolv.conf
  when: dnsmasqEtcResolvSymlink.rc != 0
  changed_when: False

- name: add /etc/resolv.conf
  template: >
    src=etc-resolv.conf.j2
    dest=/etc/resolv.conf
    owner=root group=root mode=0644

- name: set immutable bit on /etc/resolv.conf
  shell: >
    chattr +i /etc/resolv.conf
  changed_when: False
