#!/usr/bin/env bash
set -euo pipefail

function usage() {
  echo "usage: $0 <shared_path> <release_path>"
  echo "  replaces secret keys in <release_path>/wp-config.php from "
  echo "  <shared_path>/wp-content/uploads/.wp.keys"
}

function check_requirements() {
  ## check 2 args were provided
  if [ "$#" -ne 2 ]; then
    usage
    exit 1
  fi

  ## set shared and release path
  readonly SHARED_PATH=${1:-}
  readonly RELEASE_PATH=${2:-}

  ## check that both shared and release path exist
  if [[ ! -d "${SHARED_PATH}" || ! -d "${RELEASE_PATH}" ]]; then
    echo "<shared_path> and <release_path> must exist... exiting..."
    exit 1
  fi

  ## check that required files exist
  if [[ ! -f "${SHARED_PATH}/wp-content/uploads/.wp.keys" ]]; then
    echo "${SHARED_PATH}/wp-content/uploads/.wp.keys doens't exist... exiting..."
    exit 1
  fi
  if [[ ! -f "${RELEASE_PATH}/wp-config.php" ]]; then
    echo "${RELEASE_PATH}/wp-config.php doens't exist... exiting..."
    exit 1
  fi
}

## validation
check_requirements "$@"

## update wp-config.php secret keys with .wp.keys
sed -i "/#@-/r ${SHARED_PATH}/wp-content/uploads/.wp.keys" "${RELEASE_PATH}/wp-config.php"
sed -i "/#@+/,/#@-/d" "${RELEASE_PATH}/wp-config.php"
